In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
url='https://wuzzuf.net/search/jobs/?a=navbl%7Cspbl&q=data%20scientist&start=0'

response=requests.get(url)
soup = BeautifulSoup(response.content, 'lxml')
job_titles=soup.find_all('h2',{'class':'css-m604qf'})
job_titles=[job.text for job in job_titles]
company_names=soup.find_all('a',{'class':'css-17s97q8'})
company_names=[company.text for company in company_names]
locations=soup.find_all('span',{'class':'css-5wys0k'})
locations=[location.text for location in locations]
job_types=soup.find_all('div',{'class':'css-1lh32fc'})
job_types=[job.text for job in job_types]
links=soup.find_all('a',{'class':'css-o171kl'})
links=['https://wuzzuf.net'+link['href'] for link in links]
df=pd.DataFrame({'job_titles':job_titles,'company_names':company_names,'locations':locations,'job_types':job_types})
df.to_csv('jobs.csv')
df

,job_titles,company_names,locations,job_types
0,Data Scientist,Egabi FSI -,"Sheraton, Cairo, Egypt",Full TimeOn-site
1,Information Analyst – Data Scientist,Confidential -,"Maadi, Cairo, Egypt",Full TimeRemote
2,Data Scientist,Lumin -,"Sheikh Zayed, Giza, Egypt",Full TimeHybrid
3,Senior Power BI Developer,BI-Technologies -,"New Cairo, Cairo, Egypt",Full TimeHybrid
4,Data Engineer Team Lead,COB Solution -,"Maadi, Cairo, Egypt",Full TimeOn-site
5,Data Engineer,CreoTech -,"Cairo, Egypt",Full TimeOn-site
6,AI Engineer,ProVision Group -,"Maadi, Cairo, Egypt",Full TimePart TimeFreelance / ProjectHybrid
7,MLOps Engineer,Confidential -,"Cairo, Egypt",Full TimeOn-site
8,AI Engineering Manager,Link Development -,"Cairo, Egypt",Full TimeHybrid
9,Full Stack Developer,Tripnas -,"Tebin, Cairo, Egypt",Full TimeRemote
10,Recruitment Specialist,Cloud Secrets -,"Maadi, Cairo, Egypt",Full TimeOn-site
11,Mid-Level Fullstack Developer (Django + React),Nexus Analytica -,"Shorouk City, Cairo, Egypt",Full TimeOn-site
12,Full Stack Developer,Maharat -,"Riyadh, Saudi Arabia",Full TimeRemote
13,Chatbot Developer,MOBILY INFOTECH LTD INDIA -,"New Cairo, Cairo, Egypt",Full TimeHybrid
14,Scientific Officer - Water Quality & Environme...,DIAMOND ALLIANCE SERVICES -,"Kano, Nigeria",Full TimeOn-site